### ISSUE TITLE
point archive and api.effechecka.org to idigbio proxy

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/effechecka#73]
@godfoder please let me know ip address

**Comment by godfoder** [comment]
Proxy.idigbio.org (128.227.246.134) has been configured to property redirect api.effechecka.org, api.guoda.bio, archive.guoda.bio, and archive.effechecka.org to the correct new destinations. All of the pieces should be ready to receive traffic.

**Comment by jhpoelen** [comment]
@godfoder thanks . Just updated DNS entries for effechecka.org to point api/archive to proxy.idigbio.org ip. 

@mjcollin - I am assuming you'll have to point api.guoda.bio dns to 128.227.246.134 also. Does @godfoder have access?

**Comment by godfoder** [comment]
DNS is already updated on our side.

**Comment by jhpoelen** [comment]
Great! Closing issue. If I am correct, this would remove the last dependency on our old api-hack workhorse.

**Comment by jhammock** [comment]
my test query, http://api.effechecka.org/occurrences?limit=20000&taxonSelector=Animalia%2CInsecta&wktString=POLYGON%20((-150%2010%2C%20-150%2040%2C%20-50%2040%2C%20-50%2010%2C%20-150%2010))

has been successfully "submitted" three times but has not yet generated results. Related to this?

**Comment by jhpoelen** [comment]
Hmm. Looks like some hdfs issue. @godfoder has been experimenting with a new ways to deploy effechecka api. Perhaps he knows more.

A snippet from log:
```
17-08-21 22:16:41 INFO WebApi$: looking for [/guoda/data/monitor/checklist/u0=fd/u1=e2/u2=14/uuid=fde214ae-b44c-53df-8838-14d55bba8d4a]
17-08-21 22:16:41 WARN BlockReaderFactory: I/O error constructing remote block reader.
java.net.SocketException: No file descriptors available
	at sun.nio.ch.Net.socket0(Native Method)
	at sun.nio.ch.Net.socket(Net.java:411)
	at sun.nio.ch.Net.socket(Net.java:404)
	at sun.nio.ch.SocketChannelImpl.<init>(SocketChannelImpl.java:105)
	at sun.nio.ch.SelectorProviderImpl.openSocketChannel(SelectorProviderImpl.java:60)
	at java.nio.channels.SocketChannel.open(SocketChannel.java:145)
	at org.apache.hadoop.net.StandardSocketFactory.createSocket(StandardSocketFactory.java:62)
	at org.apache.hadoop.hdfs.DFSClient.newConnectedPeer(DFSClient.java:3089)
	at org.apache.hadoop.hdfs.BlockReaderFactory.nextTcpPeer(BlockReaderFactory.java:778)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReaderFromTcp(BlockReaderFactory.java:693)
	at org.apache.hadoop.hdfs.BlockReaderFactory.build(BlockReaderFactory.java:354)
	at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:617)
	at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:841)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:889)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:696)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at org.apache.parquet.hadoop.util.H2SeekableInputStream.read(H2SeekableInputStream.java:59)
	at org.apache.parquet.bytes.BytesUtils.readIntLittleEndian(BytesUtils.java:82)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:488)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:461)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:437)
	at org.apache.parquet.hadoop.ParquetFileReader$2.call(ParquetFileReader.java:259)
	at org.apache.parquet.hadoop.ParquetFileReader$2.call(ParquetFileReader.java:255)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
17-08-21 22:16:41 WARN DFSClient: Failed to connect to /10.13.44.21:50010 for block, add to deadNodes and continue. java.net.SocketException: No file descriptors available
```
